### ISSUE TITLE
how tyo use

### ISSUE THREAD

**Issue by adites01** [GoldenretriverYT/CosmosTTF#3]
i idk how to use it in my project

**Comment by retrievaaaa** [comment]
![image](https://github.com/GoldenretriverYT/CosmosTTF/assets/49924528/13230e3c-dba0-4684-9d0a-382a4add27e9)
https://github.com/GoldenretriverYT/CosmosTTF/blob/main/CosmosTTF.TestKernel/Kernel.cs

**Comment by adites01** [comment]
I meant how to import it into the project
\
